/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author user
 */
public class carga extends javax.swing.JFrame {

    /**
     * Creates new form carga1
     */
    public carga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox20 = new javax.swing.JComboBox<>();
        jComboBox21 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        bauDia2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        bauDia3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox23 = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        bauDia4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bauDia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jComboBox22 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setText("Nombre(s)");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 20));

        jLabel40.setText("Apellido(s)");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 20));

        jLabel41.setText("D.N.I.");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 20));

        jLabel42.setText("Fecha de nacimiento");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 20));

        jLabel43.setText("Teléfono");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, 20));
        jPanel6.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 230, -1));
        jPanel6.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, -1));
        jPanel6.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 250, -1));
        jPanel6.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 180, -1));
        jPanel6.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 240, -1));

        jCheckBox1.setText("Consagrado");
        jPanel6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel51.setText("Dirección");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 20));

        jLabel52.setText("Nacido en");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        jTextField36.setText("Altura");
        jPanel6.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 80, -1));

        jButton4.setText("Aceptar");
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        jButton5.setText("Cancelar");
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localidad" }));
        jPanel6.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 230, -1));

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calle" }));
        jPanel6.add(jComboBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 150, -1));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 50, 20));

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 20));

        jLabel37.setText("Nacionalidad");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 20));
        jPanel6.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 220, -1));

        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 50, 20));

        jLabel38.setText("Sexo");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 20));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Masculino");
        jPanel6.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Femenino");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jCheckBox2.setText("Habilitado");
        jPanel6.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jTabbedPane1.addTab("Fieles", jPanel6);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("El");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 20, 20));

        jLabel21.setText("de");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 20, 20));

        jTextField16.setText("mes");
        jPanel2.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, 20));

        bauDia2.setText("día");
        jPanel2.add(bauDia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, 20));

        jLabel22.setText("del");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 20, 20));

        jTextField17.setText("año");
        jPanel2.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 110, -1));

        jLabel23.setText("en");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, 20));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iglesia" }));
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 150, 20));

        jLabel24.setText("recibió su Primera Comunión.");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sacerdote" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 120, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("de");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 30, 20));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localidad" }));
        jPanel2.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, -1));

        jLabel9.setText("___________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 120, -1));

        jLabel10.setText("Párroco");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre del bautizado" }));
        jPanel2.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 340, -1));

        jButton14.setText("Cancelar");
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jButton15.setText("Aceptar");
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jButton7.setText("+");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 20));

        jLabel47.setText("Don/Doña");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 20));

        jButton21.setText("+");
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 40, 20));

        jTabbedPane1.addTab("1era. Comunión", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("el");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 20, 20));

        jLabel26.setText("de");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 20, 20));

        jTextField18.setText("mes");
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 170, 20));

        bauDia3.setText("día");
        jPanel3.add(bauDia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, -1));

        jLabel27.setText("del");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 20, 20));

        jTextField19.setText("año");
        jPanel3.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, -1));

        jLabel28.setText("en");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 20));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iglesia" }));
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        jLabel30.setText("ungido por");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, 20));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sacerdote" }));
        jPanel3.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 120, -1));

        jLabel11.setText("de");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 20, 20));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localidad" }));
        jPanel3.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 120, -1));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obispo/Sacerdote" }));
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 350, -1));

        jLabel12.setText("_________________");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel13.setText("Párroco");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel18.setText("fue confirmado");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, 20));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre del bautizado" }));
        jPanel3.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, -1));

        jButton16.setText("Cancelar");
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jButton17.setText("Aceptar");
        jPanel3.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel45.setText("Don/Doña");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 20));

        jLabel48.setText("fue padrino/madrina");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, 20));

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre padrino/madrina" }));
        jPanel3.add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 310, -1));

        jButton13.setText("+");
        jPanel3.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, 20));

        jButton20.setText("+");
        jPanel3.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 40, 20));

        jTabbedPane1.addTab("Confirmación", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("El");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 20, 20));

        jLabel32.setText("de");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 20, 20));

        jTextField21.setText("mes");
        jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 170, 20));

        bauDia4.setText("día");
        jPanel4.add(bauDia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 60, 20));

        jLabel33.setText("del");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 20, 20));

        jTextField22.setText("año");
        jPanel4.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 90, -1));

        jLabel34.setText("en");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 20, 20));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iglesia" }));
        jPanel4.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        jLabel36.setText("contrajeron matrimonio.");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sacerdote" }));
        jPanel4.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 110, -1));

        jLabel2.setText("y Doña");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, 20));

        jLabel19.setText("de");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 20, 20));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Localidad" }));
        jPanel4.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 110, -1));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiel 1" }));
        jPanel4.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiel 2" }));
        jPanel4.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 180, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("_________________");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 110, -1));

        jLabel35.setText("Párroco");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jButton18.setText("Cancelar");
        jPanel4.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jButton19.setText("Aceptar");
        jPanel4.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel46.setText("Don");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 30, 20));

        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 40, 20));

        jButton12.setText("+");
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 40, 20));

        jTabbedPane1.addTab("Matrimonio", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("el Padre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 60, 20));

        bauDia.setText("dia");
        jPanel1.add(bauDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 20));

        jLabel4.setText("de");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 20, 20));

        jTextField2.setText("mes");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 180, 20));

        jLabel5.setText("del");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 20, 20));

        jTextField3.setText("año");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 90, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sacerdote" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 360, -1));

        jLabel6.setText("bautizó a Don/Doña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 20));

        jTextField4.setText("nombre");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 310, -1));

        jLabel14.setText("hijo de la Sra.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 20));

        jLabel15.setText("y el Sr.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        jLabel16.setText("fueron padrinos");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiel 1" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("y");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 20, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiel 2" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 150, -1));

        jLabel7.setText("El");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 20, 20));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre" }));
        jPanel1.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, 20));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padre" }));
        jPanel1.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 140, -1));

        jButton10.setText("Cancelar");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jButton11.setText("Aceptar");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel44.setText("en");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 20));

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iglesia" }));
        jPanel1.add(jComboBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 340, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 30, 20));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 30, -1));

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Libro");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 30, -1));

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Folio");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 30, -1));

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("/");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 20, 20));

        jButton8.setText("+");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 160, 40, 20));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 280, -1));

        jLabel54.setText("Notas marginales");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 20));

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("______________");
        jLabel55.setToolTipText("");
        jLabel55.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, -1));

        jButton22.setText("...");
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 30, -1));

        jTabbedPane1.addTab("Bautismo", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 650, 400));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("| CARGA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bauDia;
    private javax.swing.JTextField bauDia2;
    private javax.swing.JTextField bauDia3;
    private javax.swing.JTextField bauDia4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
