/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author user
 */
public class mostrar extends javax.swing.JFrame {

    /**
     * Creates new form carga
     */
    public mostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel105 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 230, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setText("| MOSTRAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Nombre del confirmado");
        jLabel54.setOpaque(true);
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 340, 20));

        jLabel27.setText("Nacido el");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("día");
        jLabel28.setOpaque(true);
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 50, 20));

        jLabel29.setText("de");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 20, 20));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("mes");
        jLabel30.setOpaque(true);
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 260, 20));

        jLabel60.setText("del");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 20, 20));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("año");
        jLabel61.setOpaque(true);
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 90, 20));

        jLabel62.setText("bautizado en");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 20));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Nombre de la Parroquia");
        jLabel63.setOpaque(true);
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 250, 20));

        jLabel64.setText("el");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 20, 20));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("día");
        jLabel65.setOpaque(true);
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 50, 20));

        jLabel66.setText("de");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 20, 20));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("mes");
        jLabel67.setOpaque(true);
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 170, 20));

        jLabel68.setText("del");
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 30, 20));

        jLabel69.setBackground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("año");
        jLabel69.setOpaque(true);
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 50, 20));

        jLabel70.setText("Hijo de");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 60, 20));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Nombre del padre");
        jLabel71.setOpaque(true);
        jPanel3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 360, 20));

        jLabel72.setText("y de");
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 30, 20));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Nombre de la madre");
        jLabel73.setOpaque(true);
        jPanel3.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 370, 20));

        jLabel74.setText("su Padrino o Madrina es");
        jPanel3.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        jLabel75.setBackground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Nombre del padrino o madrina");
        jLabel75.setOpaque(true);
        jPanel3.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 220, 280, 20));

        jLabel76.setText("Fue confirmado en");
        jPanel3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 20));

        jLabel77.setBackground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Nombre de la Parroquia");
        jLabel77.setOpaque(true);
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 230, 20));

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel78.setText("el");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 20, 20));

        jLabel79.setBackground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("día");
        jLabel79.setOpaque(true);
        jPanel3.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 30, 20));

        jLabel80.setText("de");
        jPanel3.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 20, 20));

        jLabel81.setBackground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("mes");
        jLabel81.setOpaque(true);
        jPanel3.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 20));

        jLabel82.setText("del");
        jPanel3.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 30, 20));

        jLabel83.setBackground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("año");
        jLabel83.setOpaque(true);
        jPanel3.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 140, 20));

        jLabel84.setText("por");
        jPanel3.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 30, 20));

        jLabel85.setBackground(new java.awt.Color(255, 255, 255));
        jLabel85.setText("Nombre del Obispo o Sacerdote");
        jLabel85.setOpaque(true);
        jPanel3.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, 20));

        jLabel88.setBackground(new java.awt.Color(255, 255, 255));
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("Sacerdote");
        jLabel88.setOpaque(true);
        jPanel3.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 100, 20));

        jLabel89.setText("_________________");
        jPanel3.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel90.setText("Párroco");
        jPanel3.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jButton3.setText("<");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jButton4.setText(">");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel18.setText("Don/Doña");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jTabbedPane1.addTab("Confirmación", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setText("Don/Doña");
        jPanel2.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 20));

        jLabel93.setBackground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Nombre del bautizado");
        jLabel93.setOpaque(true);
        jPanel2.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 320, 20));

        jLabel94.setText("el");
        jPanel2.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        jLabel95.setBackground(new java.awt.Color(255, 255, 255));
        jLabel95.setText("día");
        jLabel95.setOpaque(true);
        jPanel2.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 20));

        jLabel20.setText("de");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 20, 20));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("mes");
        jLabel21.setOpaque(true);
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 20));

        jLabel22.setText("del");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 30, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("año");
        jLabel23.setOpaque(true);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, 20));

        jLabel24.setText("en ");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 20, 20));

        jLabel96.setBackground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("Nombre de la Parroquia");
        jLabel96.setOpaque(true);
        jPanel2.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 300, 20));

        jLabel39.setText(", recibió su 1era.");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 100, 90, 20));

        jLabel40.setText("Comunión.");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel97.setText("Párroco");
        jPanel2.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jLabel98.setText("_________________");
        jPanel2.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Sacerdote");
        jLabel41.setOpaque(true);
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 100, 20));

        jButton6.setText("<");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jButton7.setText(">");
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jTabbedPane1.addTab("1era. Comunión", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Nombre del bautizado");
        jLabel50.setOpaque(true);
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 320, 20));

        jLabel6.setText("hijo de");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, 20));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Nombre del padre");
        jLabel48.setOpaque(true);
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 340, 20));

        jLabel49.setText("y de");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 20));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Nombre de la madre");
        jLabel53.setOpaque(true);
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 350, 20));

        jLabel3.setText("nacido el");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("día");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("de");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 30, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("mes");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, 20));

        jLabel8.setText("del");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("año");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 50, 20));

        jLabel10.setText("ha sido BAUTIZADO en");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("día");
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, 20));

        jLabel12.setText("de");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 20, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("mes");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 130, 20));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("del");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 30, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("año");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 60, 20));

        jLabel16.setText(", según consta");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 190, 80, 20));

        jLabel17.setText("en el Libro de Bautismo ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 20));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("N° Libro");
        jLabel38.setOpaque(true);
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, 20));

        jLabel45.setText("folio");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 50, 20));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("N° Folio");
        jLabel47.setOpaque(true);
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 90, 20));

        jLabel55.setText("Son sus padrinos: Don");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 170, 20));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Nombre de la madrina");
        jLabel56.setOpaque(true);
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 340, 20));

        jLabel57.setText("y Doña");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 50, 20));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Nombre del padrino");
        jLabel58.setOpaque(true);
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 260, 20));

        jButton1.setText("<");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        jButton2.setText(">");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Nombre de la Parroquia");
        jLabel59.setOpaque(true);
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 230, 20));

        jLabel25.setText("el");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 20, 20));

        jLabel86.setText("_________________");
        jPanel1.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jLabel87.setText("Párroco");
        jPanel1.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Sacerdote");
        jLabel26.setOpaque(true);
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 100, 20));

        jLabel19.setText("Don/Doña");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 20));

        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel99.setText("______________________");
        jLabel99.setToolTipText("");
        jLabel99.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 150, -1));

        jLabel100.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel100.setText("Notas marginales");
        jPanel1.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 20));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setOpaque(true);
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 290, 20));

        jTabbedPane1.addTab("Bautismo", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("El");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 20, 20));

        jLabel32.setText("de");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 20, 20));

        jLabel33.setText("del");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 20, 20));

        jLabel34.setText("en");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 20, 20));

        jLabel43.setText("de");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 20, 20));

        jLabel46.setText("Don");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 30, 20));

        jLabel44.setText("y Doña");
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 40, 20));

        jLabel36.setText("contrajeron matrimonio.");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("día");
        jLabel51.setOpaque(true);
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, 20));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("mes");
        jLabel35.setOpaque(true);
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, 20));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("año");
        jLabel37.setOpaque(true);
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 50, 20));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Iglesia");
        jLabel52.setOpaque(true);
        jPanel4.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, 20));

        jLabel101.setBackground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("Localidad");
        jLabel101.setOpaque(true);
        jPanel4.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 120, 20));

        jLabel102.setBackground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("Nombre esposo");
        jLabel102.setOpaque(true);
        jPanel4.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 140, 20));

        jLabel103.setBackground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Nombre esposa");
        jLabel103.setOpaque(true);
        jPanel4.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 150, 20));

        jTabbedPane1.addTab("Matrimonio", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 530, 520));

        jLabel104.setText("Apellido");
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 230, -1));

        jLabel105.setText("D.N.I.");
        getContentPane().add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 20));

        jMenu1.setText("Cargar");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Mantenimiento");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuarios");
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
